import { Stat, Activity, Lead, Contact, InboxMessage } from '../types';

export const DASHBOARD_STATS: Stat[] = [
  {
    title: 'New Leads Today',
    value: '18',
    change: '+28%',
    isPositive: true,
    timeframe: 'vs yesterday',
  },
  {
    title: 'Unanswered Emails',
    value: '7',
    change: '-12%',
    isPositive: true, // fewer unanswered is positive
    timeframe: 'vs yesterday',
  },
  {
    title: 'AI Created Contacts',
    value: '142',
    change: '+8%',
    isPositive: true,
    timeframe: 'vs last week',
  },
  {
    title: 'Avg Response Time',
    value: '14.5m',
    change: '-4.2m',
    isPositive: true, // lower response time is positive
    timeframe: 'vs last week',
  },
];

export const RECENT_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    senderName: 'Sarah Jenkins',
    senderEmail: 'sarah.jenkins@nexustech.io',
    subject: 'Enterprise pricing request for LinearNexus integrations',
    time: '10 mins ago',
    status: 'pending',
    intent: 'high',
  },
  {
    id: 'act-2',
    senderName: 'David Chen',
    senderEmail: 'd.chen@orionlabs.com',
    subject: 'Question about Gmail OAuth sync reliability',
    time: '45 mins ago',
    status: 'replied',
    intent: 'medium',
  },
  {
    id: 'act-3',
    senderName: 'Elena Rostova',
    senderEmail: 'elena@cybernetica.org',
    subject: 'Inquiry regarding automated contact extraction API',
    time: '2 hours ago',
    status: 'pending',
    intent: 'high',
  },
  {
    id: 'act-4',
    senderName: 'Marcus Aurelius',
    senderEmail: 'marcus@stoiccapital.com',
    subject: 'Partnership opportunity with CRM reseller network',
    time: '4 hours ago',
    status: 'ignored',
    intent: 'low',
  },
  {
    id: 'act-5',
    senderName: 'Jessica Taylor',
    senderEmail: 'jessica@quantumflow.dev',
    subject: 'Schedule demo for sales operations team',
    time: 'Yesterday',
    status: 'replied',
    intent: 'high',
  },
];

export const PIPELINE_SUMMARIES = [
  { stage: 'New', count: 12, value: '$48,000', color: 'bg-blue-500' },
  { stage: 'Contacted', count: 8, value: '$32,500', color: 'bg-amber-500' },
  { stage: 'Qualified', count: 15, value: '$112,000', color: 'bg-emerald-500' },
  { stage: 'Proposal', count: 6, value: '$74,000', color: 'bg-purple-500' },
];

export const INBOX_THREADS: InboxMessage[] = [
  {
    id: 'inbox-1',
    sender: 'Sarah Jenkins',
    email: 'sarah.jenkins@nexustech.io',
    subject: 'Enterprise pricing request for LinearNexus integrations',
    body: 'Hi team, I would like to get a quote for our team of 150 members to connect our CRM. We need immediate SSO and dedicated support. Let me know when we can jump on a call.',
    intent: 'high',
    time: '10 mins ago',
    account: 'Gmail',
    status: 'unread',
  },
  {
    id: 'inbox-2',
    sender: 'David Chen',
    email: 'd.chen@orionlabs.com',
    subject: 'Question about Gmail OAuth sync reliability',
    body: 'Hello! I noticed that some of our incoming test emails are delayed by 5 minutes. Is there a webhooks sync or is it polling? Thank you.',
    intent: 'medium',
    time: '45 mins ago',
    account: 'Gmail',
    status: 'replied',
  },
  {
    id: 'inbox-3',
    sender: 'Elena Rostova',
    email: 'elena@cybernetica.org',
    subject: 'Inquiry regarding automated contact extraction API',
    body: 'Hi, is it possible to trigger your contact enrichment process programmatically for non-email sources? We have a signup webhook we would like to route through your LLM parsing pipeline.',
    intent: 'high',
    time: '2 hours ago',
    account: 'Outlook',
    status: 'unread',
  },
  {
    id: 'inbox-4',
    sender: 'Marcus Aurelius',
    email: 'marcus@stoiccapital.com',
    subject: 'Partnership opportunity with CRM reseller network',
    body: 'Greetings. We run a consulting firm representing CRM implementations across Europe. We would love to chat about white-labeling LinearNexus under our branding or join your affiliate channel.',
    intent: 'low',
    time: '4 hours ago',
    account: 'IMAP',
    status: 'read',
  },
  {
    id: 'inbox-5',
    sender: 'Amanda Cox',
    email: 'amanda@vertexcorp.com',
    subject: 'Billing issue - Invoice #99834',
    body: 'Hey there, we were charged twice for the team premium add-on this month. Can you check our subscription status and issue a credit? Thanks!',
    intent: 'medium',
    time: 'Yesterday',
    account: 'Gmail',
    status: 'read',
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@nexustech.io',
    company: 'NexusTech',
    jobTitle: 'VP of Sales Operations',
    source: 'Email (AI Extracted)',
    createdDate: 'May 28, 2026',
  },
  {
    id: 'contact-2',
    name: 'David Chen',
    email: 'd.chen@orionlabs.com',
    company: 'Orion Labs',
    jobTitle: 'Lead Software Architect',
    source: 'Email (AI Extracted)',
    createdDate: 'May 27, 2026',
  },
  {
    id: 'contact-3',
    name: 'Elena Rostova',
    email: 'elena@cybernetica.org',
    company: 'Cybernetica',
    jobTitle: 'Founder & CEO',
    source: 'Email (AI Extracted)',
    createdDate: 'May 26, 2026',
  },
  {
    id: 'contact-4',
    name: 'Marcus Aurelius',
    email: 'marcus@stoiccapital.com',
    company: 'Stoic Capital',
    jobTitle: 'Managing Partner',
    source: 'Email (AI Extracted)',
    createdDate: 'May 25, 2026',
  },
  {
    id: 'contact-5',
    name: 'Amanda Cox',
    email: 'amanda@vertexcorp.com',
    company: 'Vertex Corp',
    jobTitle: 'Finance Operations Lead',
    source: 'Email (AI Extracted)',
    createdDate: 'May 24, 2026',
  },
  {
    id: 'contact-6',
    name: 'Robert Vance',
    email: 'rvance@vancerefrigeration.com',
    company: 'Vance Refrigeration',
    jobTitle: 'President',
    source: 'Web Form',
    createdDate: 'May 20, 2026',
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    leadName: 'NexusTech Enterprise Expansion',
    company: 'NexusTech',
    score: 94,
    status: 'New',
    sourceEmail: 'sarah.jenkins@nexustech.io',
    owner: 'Alex Mercer',
    createdDate: 'May 28, 2026',
  },
  {
    id: 'lead-2',
    leadName: 'Orion Labs Custom CRM Integration',
    company: 'Orion Labs',
    score: 78,
    status: 'Contacted',
    sourceEmail: 'd.chen@orionlabs.com',
    owner: 'Sarah Smith',
    createdDate: 'May 27, 2026',
  },
  {
    id: 'lead-3',
    leadName: 'Cybernetica AI Enrichment Pipeline',
    company: 'Cybernetica',
    score: 89,
    status: 'Qualified',
    sourceEmail: 'elena@cybernetica.org',
    owner: 'Alex Mercer',
    createdDate: 'May 26, 2026',
  },
  {
    id: 'lead-4',
    leadName: 'Stoic Capital EU Consult Partnership',
    company: 'Stoic Capital',
    score: 45,
    status: 'New',
    sourceEmail: 'marcus@stoiccapital.com',
    owner: 'Sarah Smith',
    createdDate: 'May 25, 2026',
  },
  {
    id: 'lead-5',
    leadName: 'Vertex Corp Subscription Correction',
    company: 'Vertex Corp',
    score: 62,
    status: 'Contacted',
    sourceEmail: 'amanda@vertexcorp.com',
    owner: 'Alex Mercer',
    createdDate: 'May 24, 2026',
  },
];
